import {homeHero} from './homeHero'
import {homeServices} from './homeServices'
import {industriesSection} from './industriesSection'
import {industryImages} from './industryImages'
import {featuredInsights} from './featuredInsights'
import {homePortfolio} from './homePortfolio'
import {berryConcept} from './berryConcept'
import {clientTestimonials} from './clientTestimonials'
import {projectStrip} from './projectStrip'
import {trustedPartners} from './trustedPartners'
import {footerSettings} from './footerSettings'
import {portfolioProject} from './portfolioProject'
import {service} from './service'
import {careerRole} from './careerRole'
import {faqEntry} from './faqEntry'
import {blogPost} from './blogPost'
import {homeAbout} from './homeAbout'
import {homeStats} from './homeStats'
import {homeContact} from './homeContact'

export const schemaTypes = [homeHero, homeServices, industriesSection, industryImages, homePortfolio, berryConcept, featuredInsights, clientTestimonials, projectStrip, trustedPartners, homeAbout, homeStats, homeContact, footerSettings, portfolioProject, service, careerRole, faqEntry, blogPost]
